tasks/urls.py
from django.urls import path


from . import views

app_name='tasks'

urlpatterns = [
    # path('',views.IndexView.as_view(),name='index'),
    path('',views.CreateTask_and_list.as_view(),name="create_and_list"),
    path('todo/<int:pk>/update',views.updateTask.as_view(),name='task_update'),
    path('todo/<int:pk>/delete',views.deleteTask.as_view(),name='task_delete'),
    path('task_complete/<int:pk>',views.TaskComplete.as_view(),name='task_complete'),
    path('task_incomplete/<int:pk>',views.TaskIncomplete.as_view(),name='task_incomplete'),
]

todo/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('tasks.urls',namespace='tasks')),
]

tasks/models.py
from django.db import models

# Create your models here.


class task(models.Model):
    title=models.CharField('Task',max_length=200)
    complete = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    

tasks/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from django.views.generic import ListView,CreateView,UpdateView,DeleteView,View
from django.forms import ModelForm
from django.urls import reverse_lazy

from .models import task

# Create your views here.

# class IndexView(ListView):
#     model=task

class CreateTask_and_list(CreateView):
    template_name='tasks/task_list.html'
    model=task
    fields=['title']
    success_url=reverse_lazy('tasks:create_and_list')

    # additional context for listing all tasks
    def get_context_data(self,*args, **kwargs):
        context = super().get_context_data(*args,**kwargs)
        context["task_list"] = self.model.objects.all().order_by('-created_at')
        return context

class updateTask(UpdateView):
    model=task
    fields=['title']
    success_url=reverse_lazy('tasks:create_and_list')

class deleteTask(DeleteView):
    model=task
    success_url=reverse_lazy('tasks:create_and_list')

class TaskComplete(View):
    model=task
    def post(self,request,pk):
        print("task_complete request")
        task = get_object_or_404(self.model,pk=pk)
        print(task)
        if(task.complete == False):
            task.complete = True
            task.save()
        return HttpResponse()

class TaskIncomplete(View):
    model=task
    def post(self,request,pk):
        print("task_incomplete request")
        task = get_object_or_404(self.model,pk=pk)
        print(task)
        if(task.complete == True):
            task.complete = False
            task.save()
        return HttpResponse()

tasks/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>To do list</title>
    <!-- <style>
        .r_ef:hover{
            padding: .5em;
            background: rgb(216, 208, 208);
        }
        .r_ef{
            padding:.5em;
            background: rgb(243, 237, 237);
        }
    </style> -->
  </head>
  <body>
    
    <nav class="navbar navbar-dark bg-dark">
          <a class="navbar-brand" href="#">To Do App</a>
    </nav>
    <div class="container">
      <!-- <div class="row justify-content-center"> -->
        <!-- <div class="col-12 "> -->
          <!-- <hr class="mt-0 mb-4"> -->
          <script src="https://code.jquery.com/jquery-3.5.1.min.js"
            integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" 
            crossorigin="anonymous">
          </script>
          {% block content %}
          {% endblock %}
        <!-- </div> -->
      <!-- </div> -->
    </div>
    <footer>
      <nav class="navbar navbar-dark bg-dark">
        <a class="navbar-brand" href="#">@2020</a>
      </nav>
    </footer>
    
  </body>
</html>

tasks/templates/tasks/task_confirm_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row justify-content-center mt-4">
    <div class="col-12 col-sm-auto">
        <p>Are you sure you want to delete "{{task.title}}"?</p>
    </div>
</div>
<div class="row justify-content-center mb-4">
    <div class="col-auto col-sm-auto">
        <form action="" method="post">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger btn-sm" value="Confirm">
            <input type="submit" class="btn btn-secondary btn-sm" onclick="window.location='{% url 'tasks:create_and_list' %}'; return false;" value="Cancel">
        
        </form>
    </div>
</div>
{% endblock %}

tasks/templates/tasks/task_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row justify-content-center text-center mt-3">
    <div class="col-12">
        <h3>Update Task</h3>
        <hr>
    </div>
</div>
<div class="row justify-content-center">
    <div class="col col-sm-7">
    <form action="" method="post">
        {% csrf_token %}
            {{form | crispy}}
    </div>
</div>
<div class="row justify-content-center mb-3">
    <div class="col-auto col-sm-7 items-self-center">
        <input type="submit" class="btn btn-secondary btn-sm" value="Update">&nbsp
        <input type="submit"  class="btn btn-secondary btn-sm" onclick="window.location='{% url 'tasks:create_and_list' %}'; return false;" value="Cancel">
    </form>
    </div>
    
</div>
{% endblock %}

tasks/templates/tasks/task_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row justify-content-center mt-5">
    <div class="col-12 col-sm-6">
            <form action="" method="post">
                {% csrf_token %}
                {{ form |crispy }}
    </div>
</div>
<div class="row justify-content-center mb-4">
    <div class="col-auto col-sm-6">
                <input type="submit" class="btn btn-secondary" value="Add Task">
                <hr>
    </div>
</form>
</div>

{% for task in task_list %}
<div class="row justify-content-center mt-3 mb-2 p-2">
        <div class="col-12 col-sm-3 bg-light">
            {% if task.complete == True %}
                <p id='action_text_{{task.id}}' style="text-decoration-line:line-through">{{task.title}}</p>
            {%else%}
                <p id='action_text_{{task.id}}' style="text-decoration-line:none">{{task.title}}</p>
            {% endif %}
        </div>
        <div class="col-12 col-sm-5 bg-light">
            <div class="row align-self-center">
                <div class="col text-center">
                    <span class=" fa-2x success_icon" onclick="testComplete( '{% url 'tasks:task_incomplete' task.id %}', {{task.id}},'action_text_{{task.id}}' );return false;"
                    {% if task.complete == False %} style="display:none" {% endif %} 
                    id = 'completed_task_{{task.id}}'
                    >
                    <!--  <i class="fa fa-check-circle-o  fa-stack-1x"  style="display:none;" ></i> -->
                    <i class="fa fa-check-circle fa-stack-1x" style="color:green"></i>
                    </span>
                
                    <span class=" fa-2x success_icon" onclick="testComplete('{% url 'tasks:task_complete' task.id %}', {{task.id}},'action_text_{{task.id}}' );return false;"
                    {% if task.complete == True %} style="display:none" {% endif %}
                    id = 'incompleted_task_{{task.id}}'
                    >
                    <i class="fa fa-check-circle-o  fa-stack-1x"  ></i>
                    <!-- <i class="fa fa-check-circle fa-stack-1x"></i> -->
                    </span>
               
                </div>
                    
                <div class="col my-auto text-center">
                <a href="{% url 'tasks:task_update' task.id %}">
                <span class="edit_icon mx-auto">
                <i class="fa fa-edit edit_ico fa-2x float:right" style="color:#0275d8"></i> 
                </span>
                </a>
                </div>
                
                <div class="col my-auto text-center">
                    <a href="{% url 'tasks:task_delete' task.id %}">
                    <span class="delete_icon mx-auto">
                    <i class="fa fa-trash fa-color del_ico fa-2x "  aria-hidden="true"></i>
                    </span>
                    </a>
                </div>
               
            </div>
        </div>
        <br>
    </div>
    {% endfor %}
<script type="text/javascript">

    function testComplete(url,task_id,action_text_id){
        console.log('task',task_id);
        console.log(url);
        console.log('action_text_id:',action_text_id);
        
        action_text_el = $('#'+action_text_id);
        console.log('action_text_style:',action_text_el.css('text-decoration-line'));
        $.post(
            url,
            // {'csrfmiddlewaretoken' ='{{csrf_token}}'},
            {'csrfmiddlewaretoken' : '{{ csrf_token }}'},
            function(data,status){
                if(status == 'success'){
                    $('#completed_task_'+task_id).toggle();
                    $('#incompleted_task_'+task_id).toggle();
                    if(action_text_el.css('text-decoration-line') == "none" ){
                        $('#'+action_text_id).css({'text-decoration-line':'line-through'});
                        console.log('action_text_style:',action_text_el.css('text-decoration-line')); // to change css property
                    }
                    else{
                        $('#'+action_text_id).css({'text-decoration-line':'none'});
                        console.log('action_text_style:',action_text_el.css('text-decoration-line'));
                    }
                    
                    console.log('success');
                }
            
            }
        );
        
        console.log('ok')
    }
</script>
{% endblock content %}